<?php
$config=parse_ini_file(__DIR__."/../../jsheetconfig.ini");
if(!isset($_SESSION))
{
  session_name($config['sessionName']);
  session_start();
}
require_once($_SERVER['DOCUMENT_ROOT'].$config['appRoot']."/phpfunctions/payrollreport.php");
?>
<!DOCTYPE HTML>

<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/x-icon" href='<?php echo 'https://'.$_SERVER['HTTP_HOST'].$config['appRoot'].'/resources/app/favIcon.ico'; ?>' />

    <!-- <link rel='stylesheet' type='text/css' href='css/myQuotationStyle.css' /> -->
    <?php
      require_once($_SERVER['DOCUMENT_ROOT'].$config['appRoot']."/importScripts.php");
    ?>
    <!-- Data Table Import -->
    <link rel="stylesheet" type="text/css" href="../../adminTheme/dataTable15012020/jquery.dataTables.css">
    <script type="text/javascript" charset="utf8" src="../../adminTheme/dataTable15012020/jquery.dataTables.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.6.5/js/dataTables.buttons.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.html5.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/buttons/1.6.5/js/buttons.print.min.js"></script>

    <script type="text/javascript">
    $(document).ready( function () {
      $('#profitLossTable').DataTable({
        searching: false,
        "ordering": false,
        "pageLength": 21,
        "bLengthChange": false,
        "bInfo": false,
        "language": {
          "paginate": {
            "previous": "Previous Month",
            "next": "Next Month"
          }
        }
      });


         /*   $('#payrollreport').DataTable({
                dom: 'Bfrtip',
                buttons: [
                    'copy', 'excel', 'pdf', 'print'
                ]
            });
            */
        
        var printCounter = 0;

 <?php 
 $totalshow=false;
 if(isset($_SESSION['total'])){
   $totalshow=true;
?>
$('#payrollreport').append('<caption style="caption-center: bottom">Total Salary <?php echo number_format($_SESSION['total'],2); ?> </caption>');
<?php
 } ?>
 // Append a caption to the table before the DataTables initialisation
 
 var d = new Date();
 var filname="Payslip Report "+(d.getDate()+1)+"/"+(d.getMonth()+1)+"/"+d.getFullYear()+"-"+d.getHours()+":"+d.getMinutes();
 $('#payrollreport').DataTable( {
 
        dom: 'Bfrtip',
     buttons: [
         'copy',
         {
             extend: 'excel',
             title:''+filname,
             messageTop: 'This is payslip report table generated by automated system',
             messageBottom: 'Total Salary <?php if($totalshow){ echo number_format($_SESSION['total'],2);;} ?>'
         },
         {
             extend: 'pdf',
             title:''+filname,
             messageTop: 'This is payslip report table generated by automated system',
             messageBottom: 'Total Salary <?php if($totalshow){ echo number_format($_SESSION['total'],2);;} ?>'
         },
         {
             extend: 'print',
             title:''+filname,
             messageTop: function () {
                 printCounter++;

                 if ( printCounter === 1 ) {
                     return 'This is the first time you have printed this payslip report.';
                 }
                 else {
                     return 'You have printed this payslip report '+printCounter+' times';
                 }
             },
             messageBottom: 'Total Salary <?php if($totalshow){echo number_format($_SESSION['total'],2);unset($_SESSION['total']);} ?>'
         }
     ],
     "pageLength": 50
 } );
 var data = table.buttons.exportData();
    } );

    function changeInputType(){
      document.getElementsByName("dateMonth")[0].value = null;
      document.getElementsByName("dateYear")[0].value = null;


      var val = document.getElementById("selectDateType").value;
      if (val == 0) {
        document.getElementById("inputMonth").style.display = "block";
        document.getElementById("inputYear").style.display = "none";

        document.getElementById("inputMonthForm").required = true;
        document.getElementById("inputYearForm").required = false;

      }else {
        document.getElementById("inputMonth").style.display = "none";
        document.getElementById("inputYear").style.display = "block";

        document.getElementById("inputMonthForm").required = false;
        document.getElementById("inputYearForm").required = true;

        var i = 10;
        var d = new Date();
        var year = d.getFullYear();

        for(i=1;i<=10;i++){
          document.getElementById("year"+i).value = year;
          document.getElementById("year"+i).innerHTML = year;
          year--;
        }
      }
    }
    </script>
    <style>
        caption {
            font-size: 1.5em !important;
            color: #000 !important;
        }
    </style>
</head>
<body class="fixed-nav ">

<?php
  include $_SERVER['DOCUMENT_ROOT'].$config['appRoot']."/navMenu.php";
?>

  <div class="content-wrapper">
    <div class="container-fluid">
        <?php echo shortcut() ?>
      <!-- Breadcrumbs-->
      <ol class="breadcrumb col-md-12">
        <li class="breadcrumb-item">
          <a href="../../home.php">Dashboard</a>
        </li>
        <li class="breadcrumb-item ">Payroll Report</li>
      </ol>
    </div>
    <div class="container">
      <form method="POST" action="../../phpfunctions/payrollreport.php" class="needs-validation">
      <?php
        if (isset($_SESSION['feedback'])) {
            echo $_SESSION['feedback'];
            unset($_SESSION['feedback']);
        }
      ?>
          <div class="form-group row">
              <!-- STAFF -->
              <label for="brand" class="col-sm-1 col-form-label col-form-label-lg">*Staff</label>
              <div class="col-sm-11"   >
                  <?php dropdownlistPayrollSearchStaff() ?>
                  <div class="invalid-feedback">
                      Please choose staff
                  </div>
              </div>
          </div>
      <div class="form-group row">
          <div class="col-md-8">
            <label>Report Format</label>
            <select id="selectDateType" class="form-control" onchange="changeInputType()" name="timeCategory">
              <option value="0">Monthly</option>
              <option value="1">Yearly</option>
            </select>
          </div>

          <div class="col-md-4">
            <div id="inputMonth">
              <label id="label">By Month</label>
              <input id="inputMonthForm" class="form-control" type="month" name="dateMonth" required>
            </div>
            <div id="inputYear" style="display:none">
              <div class="form-group row">
                <label id="label">By Year</label>
                <select id="inputYearForm" class="form-control" name="dateYear">
                  <option id="year1"></option>
                  <option id="year2"></option>
                  <option id="year3"></option>
                  <option id="year4"></option>
                  <option id="year5"></option>
                  <option id="year6"></option>
                  <option id="year7"></option>
                  <option id="year8"></option>
                  <option id="year9"></option>
                  <option id="year10"></option>
                </select>
              </div>

            </div>
          </div>
      </div>
           <div class="form-group row">
              <div class="col-md-12">
                  <input type="checkbox" id="salary" name="salary" checked><label for="salary">&nbsp;Salary&nbsp;&nbsp;</label>
                  <input type="checkbox" id="allowance" name="allowance" checked><label for="allowance">&nbsp;Allowance&nbsp;&nbsp;</label>
                  <input type="checkbox" id="commissions" name="commissions" checked><label for="commissions">&nbsp;Commissions&nbsp;&nbsp;</label>
                  <input type="checkbox" id="claims" name="claims" checked><label for="claims">&nbsp;Claims&nbsp;&nbsp;</label>
                  <input type="checkbox" id="ot" name="ot" checked><label for="ot">&nbsp;OT&nbsp;&nbsp;</label>
                  <input type="checkbox" id="bonus" name="bonus" checked><label for="bonus">&nbsp;Bonus&nbsp;&nbsp;</label>
                  <input type="checkbox" id="epf" name="epf" checked><label for="epf">&nbsp;EPF&nbsp;&nbsp;</label>
                  <input type="checkbox" id="socso" name="socso" checked><label for="socso">&nbsp;SOCSO&nbsp;&nbsp;</label>
                  <input type="checkbox" id="pcb" name="pcb" checked><label for="pcb">&nbsp;PCB&nbsp;&nbsp;</label>
                  

              </div>
          </div>
      <div class="form-group row">
        <div class="col-md-12">
            <button class="btn btn-primary btn-lg btn-block" type="submit" name="payrollReportGenerate">Search</button>
        </div>
      </div>
      </form>
    </div>
    <div class="container">
    <h4 style="text-align: center;"><?php if (isset($_SESSION['datesearch'])){echo "Payslip Report ".$_SESSION['datesearch'];unset($_SESSION['datesearch']);} ?></h4>
    </div>
    <div class="container">

      <?php
      if (isset($_SESSION['payrollTable'])) {
         /* $pdf = "<a href='../profitLoss/pdf.php' target='_blank'><button>PDF</button></a>";
          $excel = "<a href='../profitLoss/excel.php' target='_blank'><button>Excel</button></a>"; */
         // echo $pdf.$excel.$_SESSION['payrollTable'];
          echo $_SESSION['payrollTable'];
          unset($_SESSION['payrollTable']);
      }
      ?>
    </div>
  </div>


    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>
        <div class="footer">
            <p>Powered by JSoft Solution Sdn. Bhd</p>
          </div>

  </div>
</body>
</html>
